# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "OrbitCaptureGgpClientLib",
    srcs = ["OrbitCaptureGgpClient.cpp"],
    hdrs = ["include/OrbitCaptureGgpClient/OrbitCaptureGgpClient.h"],
    copts = ORBIT_COPTS + [
        "-Isrc/OrbitCaptureGgpClient",
    ],
    includes = ["include"],
    deps = [
        "//src/GrpcProtos",
        "//src/OrbitBase",
    ],
)

cc_binary(
    name = "OrbitCaptureGgpClient",
    srcs = ["main.cpp"],
    copts = ORBIT_COPTS,
    deps = [
        "//src/OrbitCaptureGgpClient:OrbitCaptureGgpClientLib",
        "@abseil-cpp//absl/flags:parse",
    ],
)
