# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "Symbols",
    srcs = [
        "SymbolHelper.cpp",
        "SymbolUtils.cpp",
    ],
    hdrs = [
        "include/Symbols/MockSymbolCache.h",
        "include/Symbols/SymbolCacheInterface.h",
        "include/Symbols/SymbolHelper.h",
        "include/Symbols/SymbolUtils.h",
    ],
    copts = ORBIT_COPTS,
    includes = ["include"],
    deps = [
        "//src/GrpcProtos",
        "//src/Introspection",
        "//src/ObjectUtils",
        "//src/OrbitBase",
        "//src/SymbolProvider",
    ],
)

cc_test(
    name = "SymbolsTests",
    srcs = [
        "SymbolHelperTest.cpp",
        "SymbolUtilsTest.cpp",
    ],
    copts = ORBIT_COPTS,
    data = glob(["testdata/**"]),
    env = {"ORBIT_OVERRIDE_TESTDATA_PATH": "src/Symbols/testdata"},
    deps = [
        "//src/Symbols",
        "//src/Test:gtest_main",
        "//src/TestUtils",
    ],
)
