# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "OrbitBase",
    srcs = [
        "ExecutablePath.cpp",
        "ExecutablePathLinux.cpp",
        "ExecuteCommandLinux.cpp",
        "File.cpp",
        "GetProcessIdsLinux.cpp",
        "Logging.cpp",
        "LoggingUtils.cpp",
        "Profiling.cpp",
        "ReadFileToString.cpp",
        "SafeStrerror.cpp",
        "SimpleExecutor.cpp",
        "StringConversion.cpp",
        "ThreadPool.cpp",
        "ThreadUtilsLinux.cpp",
        "WhenAll.cpp",
        "WriteStringToFile.cpp",
    ],
    hdrs = [
        "LoggingUtils.h",
        "include/OrbitBase/Action.h",
        "include/OrbitBase/Align.h",
        "include/OrbitBase/AnyInvocable.h",
        "include/OrbitBase/AnyMovable.h",
        "include/OrbitBase/Append.h",
        "include/OrbitBase/Attributes.h",
        "include/OrbitBase/CanceledOr.h",
        "include/OrbitBase/Chunk.h",
        "include/OrbitBase/ExecutablePath.h",
        "include/OrbitBase/ExecuteCommand.h",
        "include/OrbitBase/Executor.h",
        "include/OrbitBase/File.h",
        "include/OrbitBase/Future.h",
        "include/OrbitBase/FutureHelpers.h",
        "include/OrbitBase/GetLastError.h",
        "include/OrbitBase/GetProcAddress.h",
        "include/OrbitBase/GetProcessIds.h",
        "include/OrbitBase/ImmediateExecutor.h",
        "include/OrbitBase/Logging.h",
        "include/OrbitBase/MakeUniqueForOverwrite.h",
        "include/OrbitBase/NotFoundOr.h",
        "include/OrbitBase/OsVersionWindows.h",
        "include/OrbitBase/Overloaded.h",
        "include/OrbitBase/ParameterPackTrait.h",
        "include/OrbitBase/Profiling.h",
        "include/OrbitBase/Promise.h",
        "include/OrbitBase/PromiseHelpers.h",
        "include/OrbitBase/ReadFileToString.h",
        "include/OrbitBase/Result.h",
        "include/OrbitBase/SafeStrerror.h",
        "include/OrbitBase/SharedState.h",
        "include/OrbitBase/SimpleExecutor.h",
        "include/OrbitBase/Sort.h",
        "include/OrbitBase/StopSource.h",
        "include/OrbitBase/StopToken.h",
        "include/OrbitBase/StringConversion.h",
        "include/OrbitBase/TaskGroup.h",
        "include/OrbitBase/ThreadConstants.h",
        "include/OrbitBase/ThreadPool.h",
        "include/OrbitBase/ThreadUtils.h",
        "include/OrbitBase/Typedef.h",
        "include/OrbitBase/TypedefUtils.h",
        "include/OrbitBase/UniqueResource.h",
        "include/OrbitBase/VoidToMonostate.h",
        "include/OrbitBase/WhenAll.h",
        "include/OrbitBase/WhenAny.h",
        "include/OrbitBase/WriteStringToFile.h",
    ],
    copts = ORBIT_COPTS + [
        "-Isrc/OrbitBase",
    ],
    includes = ["include"],
    deps = [
        "@abseil-cpp//absl/base:base",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/strings:strings",
        "@abseil-cpp//absl/synchronization:synchronization",
        "@abseil-cpp//absl/time:time",
        "@outcome//:outcome",
    ],
)

cc_test(
    name = "OrbitBaseTests",
    srcs = [
        "AlignTest.cpp",
        "AnyInvocableTest.cpp",
        "AnyMovableTest.cpp",
        "AppendTest.cpp",
        "CanceledOrTest.cpp",
        "ChunkTest.cpp",
        "ExecutablePathLinuxTest.cpp",
        "ExecutablePathTest.cpp",
        "ExecuteCommandLinuxTest.cpp",
        "ExecutorTest.cpp",
        "FileTest.cpp",
        "FutureHelpersTest.cpp",
        "FutureTest.cpp",
        "GetProcessIdsLinuxTest.cpp",
        "ImmediateExecutorTest.cpp",
        "LoggingUtilsTest.cpp",
        "NotFoundOrTest.cpp",
        "OverloadedTest.cpp",
        "ParameterPackTraitTest.cpp",
        "ProfilingTest.cpp",
        "PromiseHelpersTest.cpp",
        "PromiseTest.cpp",
        "ReadFileToStringTest.cpp",
        "ResultTest.cpp",
        "SimpleExecutorTest.cpp",
        "SortTest.cpp",
        "StopSourceTest.cpp",
        "StopTokenTest.cpp",
        "StringConversionTest.cpp",
        "TaskGroupTest.cpp",
        "ThreadPoolTest.cpp",
        "ThreadUtilsTest.cpp",
        "TypedefTest.cpp",
        "UniqueResourceTest.cpp",
        "WhenAllTest.cpp",
        "WhenAnyTest.cpp",
        "WriteStringToFileTest.cpp",
    ],
    copts = ORBIT_COPTS,
    data = glob(["testdata/**"]),
    env = {"ORBIT_OVERRIDE_TESTDATA_PATH": "src/OrbitBase/testdata"},
    deps = [
        "//src/OrbitBase",
        "//src/Test:gtest_main",
        "//src/TestUtils",
        "@abseil-cpp//absl/hash:hash_testing",
        "@googletest//:gtest",
    ],
)
