# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ProducerSideService",
    srcs = [
        "BuildAndStartProducerSideServerLinux.cpp",
        "ProducerSideServer.cpp",
        "ProducerSideServiceImpl.cpp",
    ],
    hdrs = [
        "BuildAndStartProducerSideServerWithUri.h",
        "include/ProducerSideService/BuildAndStartProducerSideServer.h",
        "include/ProducerSideService/ProducerSideServer.h",
        "include/ProducerSideService/ProducerSideServiceImpl.h",
    ],
    copts = ORBIT_COPTS + [
        "-Isrc/ProducerSideService",
    ],
    includes = ["include"],
    deps = [
        "//src/CaptureServiceBase",
        "//src/GrpcProtos",
        "//src/ProducerSideChannel",
    ],
)

cc_test(
    name = "ProducerSideServiceTests",
    srcs = ["ProducerSideServiceImplTest.cpp"],
    copts = ORBIT_COPTS,
    deps = [
        "//src/ProducerEventProcessor",
        "//src/ProducerSideService",
        "//src/Test:gtest_main",
        "//src/TestUtils",
    ],
)
