# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "LinuxTracing",
    srcs = [
        "ContextSwitchManager.cpp",
        "GpuTracepointVisitor.cpp",
        "LeafFunctionCallManager.cpp",
        "LibunwindstackMaps.cpp",
        "LibunwindstackMultipleOfflineAndProcessMemory.cpp",
        "LibunwindstackUnwinder.cpp",
        "LinuxTracingUtils.cpp",
        "PerfEvent.cpp",
        "PerfEventOpen.cpp",
        "PerfEventOrderedStream.cpp",
        "PerfEventProcessor.cpp",
        "PerfEventQueue.cpp",
        "PerfEventReaders.cpp",
        "PerfEventRingBuffer.cpp",
        "PythonAddressProvider.cpp",
        "PythonProfiler.cpp",
        "PythonSamplingThread.cpp",
        "SwitchesStatesNamesVisitor.cpp",
        "ThreadStateManager.cpp",
        "Tracer.cpp",
        "TracerImpl.cpp",
        "UprobeAddressMap.cpp",
        "UprobeEvents.cpp",
        "UprobesUnwindingVisitor.cpp",
    ],
    hdrs = [
        "ContextSwitchManager.h",
        "GpuTracepointVisitor.h",
        "KernelTracepoints.h",
        "LeafFunctionCallManager.h",
        "LibunwindstackMaps.h",
        "LibunwindstackMultipleOfflineAndProcessMemory.h",
        "LibunwindstackUnwinder.h",
        "LinuxTracingUtils.h",
        "LostAndDiscardedEventVisitor.h",
        "PerfEvent.h",
        "PerfEventOpen.h",
        "PerfEventOrderedStream.h",
        "PerfEventProcessor.h",
        "PerfEventQueue.h",
        "PerfEventReaders.h",
        "PerfEventRecords.h",
        "PerfEventRingBuffer.h",
        "PerfEventVisitor.h",
        "PythonAddressProvider.h",
        "PythonProfiler.h",
        "PythonSamplingThread.h",
        "SwitchesStatesNamesVisitor.h",
        "ThreadStateManager.h",
        "TracerImpl.h",
        "UprobeAddressMap.h",
        "UprobeEvents.h",
        "UprobesFunctionCallManager.h",
        "UprobesReturnAddressManager.h",
        "UprobesUnwindingVisitor.h",
        "include/LinuxTracing/Tracer.h",
        "include/LinuxTracing/TracerListener.h",
        "include/LinuxTracing/UserSpaceInstrumentationAddresses.h",
    ],
    copts = ORBIT_COPTS + [
        "-Isrc/LinuxTracing",
    ],
    includes = ["include"],
    deps = [
        "//src/GrpcProtos",
        "//src/Introspection",
        "//src/ModuleUtils",
        "//src/ObjectUtils",
        "//src/OrbitBase",
        "//src/TestUtils",
        "//third_party/libunwindstack",
        "//third_party/py-spy-ffi",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/meta:type_traits",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/strings:strings",
        "@abseil-cpp//absl/synchronization:synchronization",
    ],
)

cc_test(
    name = "LinuxTracingTests",
    srcs = [
        "ContextSwitchManagerTest.cpp",
        "GpuTracepointVisitorTest.cpp",
        "LeafFunctionCallManagerTest.cpp",
        "LibunwindstackMapsTest.cpp",
        "LibunwindstackMultipleOfflineAndProcessMemoryTest.cpp",
        "LibunwindstackUnwinderTest.cpp",
        "LinuxTracingUtilsTest.cpp",
        "LostAndDiscardedEventVisitorTest.cpp",
        "MockTracerListener.h",
        "PerfEventProcessorTest.cpp",
        "PerfEventQueueTest.cpp",
        "SwitchesStatesNamesVisitorTest.cpp",
        "ThreadStateManagerTest.cpp",
        "UprobeAddressMapTest.cpp",
        "UprobeEventsTest.cpp",
        "UprobesFunctionCallManagerTest.cpp",
        "UprobesReturnAddressManagerTest.cpp",
        "UprobesUnwindingVisitorCallchainTest.cpp",
        "UprobesUnwindingVisitorDwarfUnwindingTest.cpp",
        "UprobesUnwindingVisitorDynamicInstrumentationTest.cpp",
        "UprobesUnwindingVisitorMmapTest.cpp",
        "UprobesUnwindingVisitorTestCommon.h",
    ],
    copts = ORBIT_COPTS,
    data = glob(["testdata/**"]),
    env = {"ORBIT_OVERRIDE_TESTDATA_PATH": "src/LinuxTracing/testdata"},
    deps = [
        "//src/LinuxTracing",
        "//src/Test:gtest_main",
        "@googletest//:gtest",
    ],
)
