# Copyright (c) 2026 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[package]
name = "orbit-trampoline"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
iced-x86 = { version = "1.21", default-features = false, features = ["std", "decoder", "instr_info"] }
orbit-maps = { path = "../orbit-maps" }
orbit-ptrace = { path = "../orbit-ptrace" }
