# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "OrbitCaptureGgpService",
    srcs = [
        "OrbitCaptureGgpService.cpp",
        "OrbitCaptureGgpService.h",
        "OrbitCaptureGgpServiceImpl.cpp",
        "OrbitCaptureGgpServiceImpl.h",
        "main.cpp",
    ],
    copts = ORBIT_COPTS,
    includes = ["."],
    deps = [
        "//src/GrpcProtos",
        "//src/OrbitBase",
        "//src/OrbitClientGgp:OrbitClientGgpLib",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/flags:usage",
    ],
)
