# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "WindowsProcessLauncherService",
    srcs = ["ProcessLauncherServiceImpl.cpp"],
    hdrs = ["include/WindowsProcessLauncherService/ProcessLauncherServiceImpl.h"],
    copts = ORBIT_COPTS + [
        "-Isrc/WindowsProcessLauncherService",
    ],
    target_compatible_with = ["@platforms//os:windows"],
    includes = ["include"],
    deps = [
        "//src/GrpcProtos",
        "//src/OrbitBase",
        "//src/WindowsTracing",
        "//src/WindowsUtils",
    ],
)
