# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ProducerSideChannel",
    hdrs = ["include/ProducerSideChannel/ProducerSideChannel.h"],
    copts = ORBIT_COPTS,
    includes = ["include"],
    deps = [
        "@abseil-cpp//absl/strings:str_format",
        "@grpc//:grpc++_unsecure",
    ],
)
