// Data-driven clip list. Order matters: clips run top to bottom in ONE live viewer page.
// fields: id (NN-name: output file stem), scene (file in scenes/), title + caption (MANIFEST),
//   warmup_s: wait until the live capture is at least this old before the clip,
//   max_s: the converted clip is cut to this length, gif: false to skip the GIF,
//   crop: [x, y, w, h] in recorded device px (e.g. timeline-only clips), speed: playback factor (default: auto,
//   so a clip lands near 15 s, at most 1.75x),
//   hero: true to use the scene's ctx.mark("hero_in"/"hero_out") window in the 00-hero montage (in list order).
export const clips = [
  { id: "01-attach-record", scene: "01-attach-record.mjs", title: "Attach & record",
    caption: "Pick game_loop in the process picker, switch hooks to Uprobes and turn on Auto profile, hit Record: the timeline streams live and the capture timer ticks.", max_s: 40, hero: true },
  { id: "03-auto-profile", scene: "03-auto-profile.mjs", title: "Auto-profiling", warmup_s: 14,
    caption: "Auto-profiling picks what to hook from the samples: the status line counts hooked functions and scopes/s against the budget until it converges; the Functions view lists the hooked set.", max_s: 40, hero: true },
  { id: "02-timeline-navigation", scene: "02-timeline-nav.mjs", title: "Live timeline navigation", warmup_s: 45,
    caption: "Cursor-anchored Ctrl+wheel zoom into the live capture, drag to pan, W/S zoom and A/D pan, and tooltips on nested hooked scopes (run_frame > dispatch_game_systems > simulate_physics / update_ai, render_scene > draw_mesh).", max_s: 30, crop: [0, 0, 1600, 600], hero: true },
  { id: "04-scheduler", scene: "04-scheduler.mjs", title: "Scheduler & thread states",
    caption: "The 6-core scheduler track: game_loop's slices on each core with tooltips; clicking the thread focuses it (other threads grey out) and the thread-state strip shows Running / Sleeping.", max_s: 26, crop: [0, 0, 1600, 600], hero: true },
  { id: "05-flame-graph", scene: "05-flame.mjs", title: "Sampling flame graph",
    caption: "The sampling flame graph with named frames (run_frame, dispatch_game_systems, simulate_physics, render_scene); click highlights the function on the timeline, double-click zooms into a subtree.", max_s: 26, hero: true },
  { id: "06-callstacks", scene: "06-callstacks.mjs", title: "Top-down & bottom-up call trees",
    caption: "Top-down call tree with inclusive / self / of-parent percentages (run_frame ~88% inclusive), collapse and expand all, then the bottom-up tree from the hottest leaves to their callers.", max_s: 30, hero: false },
  { id: "07-live-table", scene: "07-live-table.mjs", title: "Live statistics & histograms",
    caption: "The Live table updates as events stream in (count, total, avg, min, max, std dev per scope); clicking simulate_physics shows its duration histogram and highlights it on the timeline.", max_s: 28, hero: true },
  { id: "08-selection-report", scene: "08-selection.mjs", title: "Time-range selection",
    caption: "Right-drag selects a time range across all threads and the report (flame graph, top-down) recomputes for just that window; left-drag on a thread's sample bar selects that thread only.", max_s: 26, hero: false },
  { id: "09-service-health", scene: "09-service-health.mjs", title: "Service self-profiling",
    caption: "orbit-service instruments itself: its CPU %, RSS, events-per-pass and ring lanes plus its own scopes, read with the cursor line across the whole capture.", max_s: 26, hero: false },
  { id: "10-code-view", scene: "10-code-view.mjs", title: "Disassembly & source",
    caption: "Right-click simulate_physics > Show disassembly and source: the service disassembles it from the running binary and interleaves the game_loop.c lines (Source / Disassembly / Both).", max_s: 30, hero: true },
  { id: "11-scope-search", scene: "11-search.mjs", title: "Scope search",
    caption: "Typing in the scope search box keeps every matching scope lit (draw_mesh, then simulate) and greys out the rest; Escape clears.", max_s: 20, crop: [0, 0, 1600, 600], hero: false },
  { id: "12-themes", scene: "12-themes.mjs", title: "Colour schemes",
    caption: "More > Color scheme recolours the whole viewer, timeline and flame graph included: Dracula, Solarized Light and Nord.", max_s: 30, hero: true },
  { id: "13-mobile-compact", scene: "13-compact-mobile.mjs", title: "Phone-sized layout",
    caption: "The same live viewer in a 390 px wide (phone) viewport: zoom and pan the timeline, then the report panel with the flame graph.", max_s: 25, hero: false },
  { id: "14-chrome-trace-import", scene: "14-chrome-trace.mjs", title: "Open a Chrome trace",
    caption: "Open a Chrome Trace Event JSON file (Perfetto traces too): processes, threads, nested slices, counters and flows are mapped onto the same timeline.", max_s: 22, hero: false },
];
