# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "OrbitCliLib",
    srcs = ["OrbitCli.cpp"],
    hdrs = [
        "include/OrbitCli/OrbitCli.h",
        "include/OrbitCli/OrbitCliOptions.h",
    ],
    copts = ORBIT_COPTS + [
        "-Isrc/OrbitCli",
    ],
    includes = ["include"],
    deps = [
        "//src/CaptureClient",
        "//src/ClientModel",
        "//src/ClientServices",
        "//src/GrpcProtos",
        "//src/OrbitBase",
        "//src/OrbitVersion",
        "//src/SymbolProvider",
        "//src/Symbols",
    ],
)

cc_binary(
    name = "OrbitCli",
    srcs = ["main.cpp"],
    copts = ORBIT_COPTS,
    deps = [
        "//src/OrbitCli:OrbitCliLib",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/flags:usage",
    ],
)
