/* tslint:disable */
/* eslint-disable */
export const __wbg_liveviewer_free: (a: number, b: number) => void;
export const liveviewer_choose_lod: (a: number, b: number, c: number, d: number) => number;
export const liveviewer_collect_instances: (a: number, b: number, c: number, d: number) => [number, number];
export const liveviewer_event_count: (a: number) => number;
export const liveviewer_ingest: (a: number, b: number, c: number) => number;
export const liveviewer_lane_count: (a: number) => number;
export const liveviewer_new: () => number;
export const liveviewer_rasterize: (a: number, b: number, c: number, d: number) => [number, number];
export const liveviewer_reset: (a: number) => void;
export const liveviewer_time_bounds: (a: number) => [number, number];
export const start_eframe: (a: any) => any;
export const markWasmPoolReady: (a: number) => void;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_mainJS: (a: number) => any;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const initThreadPool: (a: number) => any;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_1: WebAssembly.Table;
export const memory: WebAssembly.Memory;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_7: WebAssembly.Table;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h2df7efdcd861b242: (a: number, b: number) => void;
export const closure374_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha3d47ef291732239_multivalue_shim: (a: number, b: number) => [number, number];
export const __externref_table_dealloc: (a: number) => void;
export const closure1057_externref_shim: (a: number, b: number, c: any) => void;
export const closure2746_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
