# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "liborbit.so",
    srcs = [
        "LockFreeApiEventProducer.cpp",
        "LockFreeApiEventProducer.h",
        "Orbit.cpp",
        "OrbitApiVersions.h",
    ],
    copts = ORBIT_COPTS,
    linkshared = True,
    linkstatic = True,
    deps = [
        "//src/ApiInterface",
        "//src/ApiUtils",
        "//src/CaptureEventProducer",
        "//src/GrpcProtos",
        "//src/OrbitBase",
        "//src/ProducerSideChannel",
    ],
)
