# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ClientData",
    srcs = [
        "CallstackData.cpp",
        "CallstackType.cpp",
        "CaptureData.cpp",
        "DataManager.cpp",
        "FunctionInfo.cpp",
        "ModuleAndFunctionLookup.cpp",
        "ModuleData.cpp",
        "ModuleIdentifierProvider.cpp",
        "ModuleManager.cpp",
        "PostProcessedSamplingData.cpp",
        "ProcessData.cpp",
        "ScopeIdProvider.cpp",
        "ScopeStats.cpp",
        "ScopeStatsCollection.cpp",
        "ScopeTreeTimerData.cpp",
        "ThreadTrackDataProvider.cpp",
        "TimerChain.cpp",
        "TimerData.cpp",
        "TimerTrackDataIdManager.cpp",
        "TimestampIntervalSet.cpp",
        "TracepointData.cpp",
        "UserDefinedCaptureData.cpp",
    ],
    hdrs = [
        "include/ClientData/ApiStringEvent.h",
        "include/ClientData/ApiTrackValue.h",
        "include/ClientData/CallstackData.h",
        "include/ClientData/CallstackEvent.h",
        "include/ClientData/CallstackInfo.h",
        "include/ClientData/CallstackType.h",
        "include/ClientData/CaptureData.h",
        "include/ClientData/CaptureDataHolder.h",
        "include/ClientData/CgroupAndProcessMemoryInfo.h",
        "include/ClientData/DataManager.h",
        "include/ClientData/FastRenderingUtils.h",
        "include/ClientData/FunctionInfo.h",
        "include/ClientData/LinuxAddressInfo.h",
        "include/ClientData/MockScopeIdProvider.h",
        "include/ClientData/MockScopeStatsCollection.h",
        "include/ClientData/ModuleAndFunctionLookup.h",
        "include/ClientData/ModuleData.h",
        "include/ClientData/ModuleIdentifier.h",
        "include/ClientData/ModuleIdentifierProvider.h",
        "include/ClientData/ModuleInMemory.h",
        "include/ClientData/ModuleManager.h",
        "include/ClientData/ModulePathAndBuildId.h",
        "include/ClientData/PageFaultsInfo.h",
        "include/ClientData/PostProcessedSamplingData.h",
        "include/ClientData/ProcessData.h",
        "include/ClientData/ScopeId.h",
        "include/ClientData/ScopeIdProvider.h",
        "include/ClientData/ScopeInfo.h",
        "include/ClientData/ScopeStats.h",
        "include/ClientData/ScopeStatsCollection.h",
        "include/ClientData/ScopeTreeTimerData.h",
        "include/ClientData/SystemMemoryInfo.h",
        "include/ClientData/ThreadStateSliceInfo.h",
        "include/ClientData/ThreadTrackDataManager.h",
        "include/ClientData/ThreadTrackDataProvider.h",
        "include/ClientData/TimerChain.h",
        "include/ClientData/TimerData.h",
        "include/ClientData/TimerDataInterface.h",
        "include/ClientData/TimerDataManager.h",
        "include/ClientData/TimerTrackDataIdManager.h",
        "include/ClientData/TimestampIntervalSet.h",
        "include/ClientData/TracepointCustom.h",
        "include/ClientData/TracepointData.h",
        "include/ClientData/TracepointEventInfo.h",
        "include/ClientData/TracepointInfo.h",
        "include/ClientData/UserDefinedCaptureData.h",
        "include/ClientData/WineSyscallHandlingMethod.h",
    ],
    copts = ORBIT_COPTS + [
        "-Isrc/ClientData",
    ],
    includes = ["include"],
    deps = [
        "//src/ApiInterface",
        "//src/ClientProtos",
        "//src/Containers",
        "//src/GrpcProtos",
        "//src/ModuleUtils",
        "//src/ObjectUtils",
        "//src/OrbitBase",
        "//third_party/xxHash-r42:xxhash",
    ],
)

cc_test(
    name = "ClientDataTests",
    srcs = [
        "CallstackDataTest.cpp",
        "CaptureDataTest.cpp",
        "DataManagerTest.cpp",
        "FastRenderingUtilsTest.cpp",
        "FunctionInfoTest.cpp",
        "ModuleDataTest.cpp",
        "ModuleIdentifierProviderTest.cpp",
        "ModuleIdentifierTest.cpp",
        "ModuleManagerTest.cpp",
        "ModulePathAndBuildIdTest.cpp",
        "ProcessDataTest.cpp",
        "ScopeIdProviderTest.cpp",
        "ScopeInfoTest.cpp",
        "ScopeStatsCollectionTest.cpp",
        "ScopeTreeTimerDataTest.cpp",
        "ThreadTrackDataManagerTest.cpp",
        "ThreadTrackDataProviderTest.cpp",
        "TimerDataTest.cpp",
        "TimerTrackDataIdManagerTest.cpp",
        "TimestampIntervalSetTest.cpp",
        "TracepointDataTest.cpp",
        "UserDefinedCaptureDataTest.cpp",
    ],
    copts = ORBIT_COPTS,
    data = glob(["testdata/**"]),
    env = {"ORBIT_OVERRIDE_TESTDATA_PATH": "src/ClientData/testdata"},
    deps = [
        "//src/ClientData",
        "//src/Test:gtest_main",
        "//src/TestUtils",
        "@abseil-cpp//absl/hash:hash_testing",
    ],
)
