# Copyright (c) 2026 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

sh_binary(
    name = "expand_version",
    srcs = ["expand_version.sh"],
    visibility = ["//visibility:public"],
)
