# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "StringManager",
    srcs = ["StringManager.cpp"],
    hdrs = ["include/StringManager/StringManager.h"],
    copts = ORBIT_COPTS,
    includes = ["include"],
    deps = [
        "//src/OrbitBase",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/strings:strings",
        "@abseil-cpp//absl/synchronization:synchronization",
    ],
)

cc_test(
    name = "StringManagerTests",
    srcs = ["StringManagerTest.cpp"],
    copts = ORBIT_COPTS,
    deps = [
        "//src/StringManager",
        "//src/Test:gtest_main",
    ],
)
