# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "OrbitGl",
    srcs = [
        "AnnotationTrack.cpp",
        "AsyncTrack.cpp",
        "BasicPageFaultsTrack.cpp",
        "BatchRenderGroup.cpp",
        "Batcher.cpp",
        "Button.cpp",
        "CGroupAndProcessMemoryTrack.cpp",
        "CallTreeView.cpp",
        "CallstackThreadBar.cpp",
        "CaptureStats.cpp",
        "CaptureViewElement.cpp",
        "CaptureWindow.cpp",
        "FormatCallstackForTooltip.cpp",
        "FrameTrack.cpp",
        "FrameTrackOnlineProcessor.cpp",
        "GlCanvas.cpp",
        "GlSlider.cpp",
        "GpuDebugMarkerTrack.cpp",
        "GpuSubmissionTrack.cpp",
        "GpuTrack.cpp",
        "GraphTrack.cpp",
        "GraphTrackDataAggregator.cpp",
        "IntrospectionWindow.cpp",
        "LineGraphTrack.cpp",
        "LiveFunctionsController.cpp",
        "MajorPageFaultsTrack.cpp",
        "ManualInstrumentationManager.cpp",
        "MemoryTrack.cpp",
        "MinorPageFaultsTrack.cpp",
        "MultivariateTimeSeries.cpp",
        "OpenGlBatcher.cpp",
        "OrbitApp.cpp",
        "PageFaultsTrack.cpp",
        "PickingManager.cpp",
        "PrimitiveAssembler.cpp",
        "QtTextRenderer.cpp",
        "SamplingReport.cpp",
        "SchedulerTrack.cpp",
        "SchedulingStats.cpp",
        "SelectionData.cpp",
        "SimpleTimings.cpp",
        "SymbolLoader.cpp",
        "SystemMemoryTrack.cpp",
        "ThreadBar.cpp",
        "ThreadColor.cpp",
        "ThreadStateBar.cpp",
        "ThreadTrack.cpp",
        "TimeGraph.cpp",
        "TimelineTicks.cpp",
        "TimelineUi.cpp",
        "TimerInfosIterator.cpp",
        "TimerTrack.cpp",
        "TracepointThreadBar.cpp",
        "Track.cpp",
        "TrackContainer.cpp",
        "TrackHeader.cpp",
        "TrackManager.cpp",
        "TrackRenderHelper.cpp",
        "TrackTestData.cpp",
        "TranslationStack.cpp",
        "TriangleToggle.cpp",
        "VerticalSizer.cpp",
        "Viewport.cpp",
    ],
    hdrs = [
        "include/OrbitGl/AnnotationTrack.h",
        "include/OrbitGl/AsyncTrack.h",
        "include/OrbitGl/BasicPageFaultsTrack.h",
        "include/OrbitGl/BatchRenderGroup.h",
        "include/OrbitGl/Batcher.h",
        "include/OrbitGl/BatcherInterface.h",
        "include/OrbitGl/Button.h",
        "include/OrbitGl/CGroupAndProcessMemoryTrack.h",
        "include/OrbitGl/CallTreeView.h",
        "include/OrbitGl/CallstackThreadBar.h",
        "include/OrbitGl/CaptureStats.h",
        "include/OrbitGl/CaptureViewElement.h",
        "include/OrbitGl/CaptureWindow.h",
        "include/OrbitGl/CaptureWindowDebugInterface.h",
        "include/OrbitGl/CoreMath.h",
        "include/OrbitGl/DataViewFactory.h",
        "include/OrbitGl/FormatCallstackForTooltip.h",
        "include/OrbitGl/FrameTrack.h",
        "include/OrbitGl/FrameTrackOnlineProcessor.h",
        "include/OrbitGl/Geometry.h",
        "include/OrbitGl/GlCanvas.h",
        "include/OrbitGl/GlSlider.h",
        "include/OrbitGl/GlUtils.h",
        "include/OrbitGl/GpuDebugMarkerTrack.h",
        "include/OrbitGl/GpuSubmissionTrack.h",
        "include/OrbitGl/GpuTrack.h",
        "include/OrbitGl/GraphTrack.h",
        "include/OrbitGl/GraphTrackDataAggregator.h",
        "include/OrbitGl/IntrospectionWindow.h",
        "include/OrbitGl/LineGraphTrack.h",
        "include/OrbitGl/LiveFunctionsController.h",
        "include/OrbitGl/MainWindowInterface.h",
        "include/OrbitGl/MajorPageFaultsTrack.h",
        "include/OrbitGl/ManualInstrumentationManager.h",
        "include/OrbitGl/MemoryTrack.h",
        "include/OrbitGl/MinorPageFaultsTrack.h",
        "include/OrbitGl/MockTimelineInfo.h",
        "include/OrbitGl/MultivariateTimeSeries.h",
        "include/OrbitGl/OpenGlBatcher.h",
        "include/OrbitGl/OrbitApp.h",
        "include/OrbitGl/PageFaultsTrack.h",
        "include/OrbitGl/PickingManager.h",
        "include/OrbitGl/PrimitiveAssembler.h",
        "include/OrbitGl/QtTextRenderer.h",
        "include/OrbitGl/SamplingReport.h",
        "include/OrbitGl/SchedulerTrack.h",
        "include/OrbitGl/SchedulingStats.h",
        "include/OrbitGl/SelectionData.h",
        "include/OrbitGl/ShortenStringWithEllipsis.h",
        "include/OrbitGl/SimpleTimings.h",
        "include/OrbitGl/StaticTimeGraphLayout.h",
        "include/OrbitGl/SymbolLoader.h",
        "include/OrbitGl/SystemMemoryTrack.h",
        "include/OrbitGl/TextRenderer.h",
        "include/OrbitGl/TextRendererInterface.h",
        "include/OrbitGl/ThreadBar.h",
        "include/OrbitGl/ThreadColor.h",
        "include/OrbitGl/ThreadStateBar.h",
        "include/OrbitGl/ThreadTrack.h",
        "include/OrbitGl/TimeGraph.h",
        "include/OrbitGl/TimeGraphLayout.h",
        "include/OrbitGl/TimelineInfoInterface.h",
        "include/OrbitGl/TimelineTicks.h",
        "include/OrbitGl/TimelineUi.h",
        "include/OrbitGl/Timer.h",
        "include/OrbitGl/TimerInfosIterator.h",
        "include/OrbitGl/TimerTrack.h",
        "include/OrbitGl/TracepointThreadBar.h",
        "include/OrbitGl/Track.h",
        "include/OrbitGl/TrackContainer.h",
        "include/OrbitGl/TrackControlInterface.h",
        "include/OrbitGl/TrackHeader.h",
        "include/OrbitGl/TrackManager.h",
        "include/OrbitGl/TrackRenderHelper.h",
        "include/OrbitGl/TrackTestData.h",
        "include/OrbitGl/TranslationStack.h",
        "include/OrbitGl/TriangleToggle.h",
        "include/OrbitGl/VariableTrack.h",
        "include/OrbitGl/VerticalSizer.h",
        "include/OrbitGl/Viewport.h",
    ],
    copts = ORBIT_COPTS,
    defines = ["WIN32_LEAN_AND_MEAN"],
    includes = ["include"],
    deps = [
        "//src/CaptureClient",
        "//src/CaptureFileInfo",
        "//src/ClientData",
        "//src/ClientFlags",
        "//src/ClientModel",
        "//src/ClientServices",
        "//src/ClientSymbols",
        "//src/CodeReport",
        "//src/Containers",
        "//src/DataViews",
        "//src/DisplayFormats",
        "//src/GrpcProtos",
        "//src/Http",
        "//src/OrbitBase",
        "//src/OrbitPaths",
        "//src/OrbitVersion",
        "//src/PresetFile",
        "//src/RemoteSymbolProvider",
        "//src/StringManager",
        "//src/SymbolProvider",
        "//src/Symbols",
        "//third_party/gte",
        "@qt5//:Gui",
    ],
)

cc_test(
    name = "OrbitGlTests",
    srcs = [
        "BatchRenderGroupTest.cpp",
        "BatcherTest.cpp",
        "ButtonTest.cpp",
        "CaptureStatsTest.cpp",
        "CaptureViewElementTest.cpp",
        "CaptureViewElementTester.cpp",
        "CaptureWindowTest.cpp",
        "CoreMathTest.cpp",
        "FormatCallstackForTooltipTest.cpp",
        "GlUtilsTest.cpp",
        "GpuTrackTest.cpp",
        "GraphTrackDataAggregatorTest.cpp",
        "MockBatcher.cpp",
        "MockTextRenderer.cpp",
        "MultivariateTimeSeriesTest.cpp",
        "OpenGlBatcherTest.cpp",
        "PageFaultsTrackTest.cpp",
        "PickingManagerTest.cpp",
        "PrimitiveAssemblerTest.cpp",
        "ShortenStringWithEllipsisTest.cpp",
        "SimpleTimingsTest.cpp",
        "SliderTest.cpp",
        "ThreadTrackTest.cpp",
        "TimeGraphTest.cpp",
        "TimelineTicksTest.cpp",
        "TimelineUiTest.cpp",
        "TimerInfosIteratorTest.cpp",
        "TrackHeaderTest.cpp",
        "TrackManagerTest.cpp",
        "TranslationStackTest.cpp",
        "ViewportTest.cpp",
        "include/OrbitGl/CaptureViewElementTester.h",
        "include/OrbitGl/MockBatcher.h",
        "include/OrbitGl/MockTextRenderer.h",
        "include/OrbitGl/PickingManagerTest.h",
    ],
    copts = ORBIT_COPTS,
    deps = [
        "//src/OrbitGl",
        "//src/Test:gtest_main",
    ],
)
