# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "CommandLineUtils",
    srcs = ["CommandLineUtils.cpp"],
    hdrs = ["include/CommandLineUtils/CommandLineUtils.h"],
    copts = ORBIT_COPTS,
    includes = ["include"],
    deps = [
        "//src/ClientFlags",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/flags:flag",
        "@qt5//:Core",
    ],
)

cc_test(
    name = "CommandLineUtilsTests",
    srcs = ["CommandLineUtilsTest.cpp"],
    copts = ORBIT_COPTS,
    deps = [
        "//src/CommandLineUtils",
        "//src/Test:gtest_main",
    ],
)
