# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ProcessService",
    srcs = [
        "Process.cpp",
        "ProcessList.cpp",
        "ProcessServiceImpl.cpp",
        "ProcessServiceUtils.cpp",
    ],
    hdrs = [
        "ProcessServiceUtils.h",
        "include/ProcessService/CpuTime.h",
        "include/ProcessService/Process.h",
        "include/ProcessService/ProcessList.h",
        "include/ProcessService/ProcessServiceImpl.h",
    ],
    copts = ORBIT_COPTS + [
        "-Isrc/ProcessService",
    ],
    includes = ["include"],
    deps = [
        "//src/GrpcProtos",
        "//src/ModuleUtils",
        "//src/ObjectUtils",
        "//src/OrbitBase",
        "//src/Symbols",
    ],
)

cc_test(
    name = "ProcessServiceTests",
    srcs = [
        "ProcessListTest.cpp",
        "ProcessServiceUtilsTest.cpp",
        "ProcessTest.cpp",
    ],
    copts = ORBIT_COPTS,
    data = glob(["testdata/**"]),
    env = {"ORBIT_OVERRIDE_TESTDATA_PATH": "src/ProcessService/testdata"},
    deps = [
        "//src/ProcessService",
        "//src/Test:gtest_main",
        "//src/TestUtils",
    ],
)
