# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:copts.bzl", "ORBIT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "OrbitPaths",
    srcs = ["Paths.cpp"],
    hdrs = ["include/OrbitPaths/Paths.h"],
    copts = ORBIT_COPTS,
    includes = ["include"],
    deps = [
        "//src/OrbitBase",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "OrbitPathsTests",
    srcs = ["PathsTest.cpp"],
    copts = ORBIT_COPTS,
    deps = [
        "//src/OrbitPaths",
        "//src/Test:gtest_main",
        "//src/TestUtils",
    ],
)
