# Copyright (c) 2020 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel/qt:rules.bzl", "qt_cc_library", "qt_cc_test")
load("//bazel:copts.bzl", "ORBIT_COPTS")

package(default_visibility = ["//visibility:public"])

qt_cc_library(
    name = "OrbitQt",
    srcs = [
        "AnnotatingSourceCodeDialog.cpp",
        "CallTreeViewItemModel.cpp",
        "CallTreeWidget.cpp",
        "CaptureOptionsDialog.cpp",
        "CaptureWindowDebugWidget.cpp",
        "DebugTabWidget.cpp",
        "ElidedLabel.cpp",
        "FilterPanelWidget.cpp",
        "FilterPanelWidgetAction.cpp",
        "HistogramWidget.cpp",
        "MultipleOfSpinBox.cpp",
        "MultipleOfValidator.cpp",
        "TimeGraphLayoutWidget.cpp",
        "TrackConfigurationWidget.cpp",
        "TrackTypeItemModel.cpp",
        "opengldetect.cpp",
        "orbitaboutdialog.cpp",
        "orbitdataviewpanel.cpp",
        "orbiteventiterator.cpp",
        "orbitglwidget.cpp",
        "orbitlivefunctions.cpp",
        "orbitmainwindow.cpp",
        "orbitsamplingreport.cpp",
        "orbittablemodel.cpp",
        "orbittreeview.cpp",
    ],
    hdrs = [
        "include/OrbitQt/MultipleOfSpinBox.h",
        "include/OrbitQt/MultipleOfValidator.h",
        "include/OrbitQt/opengldetect.h",
        "include/OrbitQt/orbitaboutdialog.h",
        "include/OrbitQt/resource.h",
        "include/OrbitQt/types.h",
    ],
    moc_hdrs = [
        "include/OrbitQt/AnnotatingSourceCodeDialog.h",
        "include/OrbitQt/CallTreeViewItemModel.h",
        "include/OrbitQt/CallTreeWidget.h",
        "include/OrbitQt/CaptureOptionsDialog.h",
        "include/OrbitQt/CaptureWindowDebugWidget.h",
        "include/OrbitQt/CustomSignalsTreeView.h",
        "include/OrbitQt/CutoutWidget.h",
        "include/OrbitQt/DebugTabWidget.h",
        "include/OrbitQt/ElidedLabel.h",
        "include/OrbitQt/FilterPanelWidget.h",
        "include/OrbitQt/FilterPanelWidgetAction.h",
        "include/OrbitQt/HistogramWidget.h",
        "include/OrbitQt/TimeGraphLayoutWidget.h",
        "include/OrbitQt/TrackConfigurationWidget.h",
        "include/OrbitQt/TrackTypeItemModel.h",
        "include/OrbitQt/orbitdataviewpanel.h",
        "include/OrbitQt/orbiteventiterator.h",
        "include/OrbitQt/orbitglwidget.h",
        "include/OrbitQt/orbitlivefunctions.h",
        "include/OrbitQt/orbitmainwindow.h",
        "include/OrbitQt/orbitsamplingreport.h",
        "include/OrbitQt/orbittablemodel.h",
        "include/OrbitQt/orbittreeview.h",
    ],
    ui = [
        "CallTreeWidget.ui",
        "CaptureOptionsDialog.ui",
        "CaptureWindowDebugWidget.ui",
        "DebugTabWidget.ui",
        "FilterPanelWidget.ui",
        "TrackConfigurationWidget.ui",
        "orbitaboutdialog.ui",
        "orbitdataviewpanel.ui",
        "orbiteventiterator.ui",
        "orbitlivefunctions.ui",
        "orbitmainwindow.ui",
        "orbitsamplingreport.ui",
    ],
    copts = ORBIT_COPTS,
    include_dirs = [
        ".",
        "include",
    ],
    deps = [
        "//src/CaptureFileInfo",
        "//src/ClientFlags",
        "//src/ClientSymbols",
        "//src/CodeViewer",
        "//src/ConfigWidgets",
        "//src/DisplayFormats",
        "//src/OrbitGl",
        "//src/OrbitSshQt",
        "//src/OrbitVersion",
        "//src/QtUtils",
        "//src/SessionSetup",
        "//src/SourcePathsMapping",
        "//src/SourcePathsMappingUI",
        "//src/SymbolProvider",
        "//src/SyntaxHighlighter",
        "//src/UtilWidgets",
        "@qt5//:Core",
        "@qt5//:Widgets",
    ],
)

qt_cc_test(
    name = "OrbitQtTests",
    srcs = [
        "AnnotatingSourceCodeDialogTest.cpp",
        "CallTreeViewItemModelTest.cpp",
        "CaptureWindowDebugWidgetTest.cpp",
        "DebugTabWidgetTest.cpp",
        "HistogramWidgetTest.cpp",
        "MultipleOfValidatorTest.cpp",
        "TimeGraphLayoutWidgetTest.cpp",
        "TrackTypeItemModelTest.cpp",
    ],
    copts = ORBIT_COPTS,
    data = glob(["testdata/**"]),
    env = {"ORBIT_OVERRIDE_TESTDATA_PATH": "src/OrbitQt/testdata"},
    includes = ["."],
    deps = [
        "//src/OrbitGl",
        "//src/OrbitQt",
        "//src/Test:gtest_qtgui_main",
        "@qt5//:Test",
    ],
)
